# site.yml
---
- hosts: all
  tasks:
    - name: ensure git is installed
      become: true
      package: 
        name: git
        state: present
    - name: ensure git configs
      copy:
        src: gitconfig.dist
        dest: /home/vagrant/.gitconfig

