---
- name: ensure git is installed
  become: true
  package:
    name: git
    state: present

- name: ensure git config
  ini_file:
    dest: "{{ ansible_user_dir }}/.gitconfig"
    section: "{{ item.ns }}"
    option: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { ns: user, name: email, value: "{{ git_user_email }}" }
    - { ns: user, name: name, value: "{{ git_user_name }}" }
    - { ns: push, name: default, value: simple }
    - {
        ns: core,
        name: excludesfile,
        value: "{{ ansible_user_dir }}/.gitignore",
      }
